accountApp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountApp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

piecesPinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profiles/', include('profileApp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscribe/', include('subscribeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileApp/urls.py
from django.urls import path

from profileApp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileApp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountApp/models.py
from django.db import models

# Create your models here.

articleApp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectApp.models import Project


# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='article')
    project = models.ForeignKey(Project,  null=True, on_delete=models.SET_NULL, related_name='article')

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

accountApp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountApp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountApp.forms import AccountUpdateForm
from accountApp.decorators import account_ownership_required
from articleApp.models import Article

has_ownership = [account_ownership_required, login_required]


# Create your views here.

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountApp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountApp/detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('home')
    template_name = 'accountApp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountApp:login')
    template_name = 'accountApp/delete.html'

accountApp/templates/accountApp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <form action="{% url 'accountApp:create' %}" method="post">
        <div>
            <h4 class="mb-4">
                Sign up
            </h4>
        </div>
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountApp/templates/accountApp/delete.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <form action="{% url 'accountApp:delete' pk=target_user.pk %}" method="post">
        <div>
            <h4 class="mb-4">
                Quit
            </h4>
        </div>
        {% csrf_token %}

        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountApp/templates/accountApp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="" style="height: 15rem; width: 15rem; border-radius: 10rem; margin-bottom: 1rem;">
            <h2>
                {{ target_user.profile.nickname }}
                {% if target_user == user %}
                <a href="{% url 'profileApp:update' pk=target_user.profile.pk %}" class="material-icons" style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
                    edit
                </a>
                {% endif %}
            </h2>
            <h5 style="margin-bottom: 3rem;">
                {{ target_user.profile.message }}
            </h5>
            {% else %}
                {% if target_user == user %}
                <a href="{% url 'profileApp:create' %}">
                    <h2>
                        Create Profile
                    </h2>
                </a>
                {% else %}
                <h2>Empty Profile</h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
            <a href="{% url 'accountApp:update' pk=user.pk %}" class="material-icons" style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
                    settings
            </a>
            <a href="{% url 'accountApp:delete' pk=user.pk %}" class="material-icons" style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;">
                    cancel
            </a>
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>
{% endblock %}

accountApp/templates/accountApp/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}

                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>
{% endblock %}

accountApp/templates/accountApp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <form action="{% url 'accountApp:update' pk=target_user.pk %}" method="post">
        <div>
            <h4 class="mb-4">
                Changing Info
            </h4>
        </div>
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}