accountApp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountApp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

piecesPinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profiles/', include('profileApp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscribe/', include('subscribeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectApp/urls.py
from django.urls import path

from projectApp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectApp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail')
]

subscribeApp/urls.py
from django.urls import path

from projectApp.views import ProjectListView, ProjectCreateView, ProjectDetailView
from subscribeApp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeApp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

articleApp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectApp.models import Project


# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='article')
    project = models.ForeignKey(Project,  null=True, on_delete=models.SET_NULL, related_name='article')

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

projectApp/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    image = models.ImageField(upload_to='project/', null=False)
    title = models.CharField(max_length=20, null=False)
    description = models.TextField(max_length=200, null=True)

    created_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectApp/forms.py
from django.forms import ModelForm

from projectApp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image']

projectApp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.list import MultipleObjectMixin

from articleApp.models import Article
from projectApp.forms import ProjectCreationForm
from projectApp.models import Project
from subscribeApp.models import Subscription


# Create your views here.
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projects/create.html'

    def get_success_url(self):
        return reverse('projectApp:detail', kwargs={'pk':self.object.pk})

class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projects/detail.html'

    paginate_by = 25
    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user

        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None
        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, subscription=subscription, **kwargs)

class ProjectListView(ListView):
    model = Project
    template_name = 'projects/list.html'
    context_object_name = 'project_list'
    paginate_by = 25

projectApp/templates/projects/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <form action="{% url 'projectApp:create' %}" method="post" enctype="multipart/form-data">
        <div>
            <h4 class="mb-4">
                Project Create
            </h4>
        </div>
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

projectApp/templates/projects/detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

            <img src="{{ target_project.image.url }}" alt="" style="height: 15rem; width: 15rem; border-radius: 10rem; margin-bottom: 1rem;">
            <h2>
                {{ target_project.title }}
            </h2>
            <h6 style="margin-bottom: 3rem;">
                {{ target_project.created_at }}
            </h6>
            <h5 style="margin-bottom: 3rem;">
                {{ target_project.description }}
            </h5>
        </div>

        {% if user.is_authenticated %}
        <div class="text-center">
            {% if not subscription %}
            <a href="{% url 'subscribeApp:subscribe' %}?project_pk={{ target_project.pk }}" class="btn btn-primary rounded-pill px-4 mb-5">
                Subscribe
            </a>
            {% else %}
            <a href="{% url 'subscribeApp:subscribe' %}?project_pk={{ target_project.pk }}" class="btn btn-dark rounded-pill px-4 mb-5">
                Unsubscribe
            </a>
            {% endif %}
        </div>
        {% endif %}

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>
{% endblock %}

projectApp/templates/projects/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .container {
        padding: 0;
        margin: 0 auto;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 7rem;
        height: 7rem;
        object-fit: cover;
        border-radius: 1rem;
    }
</style>

{% if project_list %}
<div class="container">
    {% for project in project_list %}
        <a href="{% url 'projectApp:detail' pk=project.pk %}">
            {% include 'snippets/project_card.html' with project=project%}
        </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div class="text-center">
    <h1>No Projects</h1>
</div>
{% endif %}


{% include 'snippets/pagination.html' with page_obj=page_obj %}

<div style="text-align: center;">
    <a href="{% url 'projectApp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
        Create Project
    </a>
</div>

{% endblock %}