accountApp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountApp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleApp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleApp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleApp'

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleApp/list.html'), name='list'),

    path('create/', ArticleCreateView.as_view(template_name='articleApp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleApp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleApp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleApp/delete.html'), name='delete'),

]

piecesPinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profiles/', include('profileApp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscribe/', include('subscribeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectApp/urls.py
from django.urls import path

from projectApp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectApp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail')
]

subscribeApp/urls.py
from django.urls import path

from projectApp.views import ProjectListView, ProjectCreateView, ProjectDetailView
from subscribeApp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeApp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}

    <hr>

    {% block content %}

    {% endblock %}

    <hr>

    {% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div class="text-center">
    <div class="footer_nav">
        <span>Notices</span> |
        <span>Contact</span> |
        <span>Introduction</span>
    </div>
    <div class="mt-2">
        <h6 class="logo">Pieces' Pinterest</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Pragmatic</title>
    <!--    BOOTSTRAP Link    -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!--    Google Fonts Link-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!--    Google Material Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!--    Default CSS Link    -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'), url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="text-center mt-4">
    <div>
        <h1 class="logo">Pieces' Pinterest</h1>
    </div>
    <div class="header_nav">
        <a href="{% url 'articleApp:list' %}" class="header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectApp:list' %}" class="header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeApp:list' %}" class="header_nav">
            <span>Subscription</span>
        </a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accountApp:login' %}?next={{ request.path }}" class="header_nav">
            <span>login</span>
        </a>
        <a href="{% url 'accountApp:create' %}" class="header_nav">
            <span>Sign Up</span>
        </a>
        {% else %}
        <a href="{% url 'accountApp:detail' pk=user.pk %}" class="header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountApp:logout' %}?next={% url 'home' %}" class="header_nav">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>